#!/usr/bin/env bash

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
--menu)
  rofi -show drun -theme "$HOME"/.config/bspwm/src/rofi-themes/Launcher.rasi
  ;;
--rice)
  RiceSelector
  ;;
--terminal)
  Term --terminal
  ;;
--floating)
  Term --floating
  ;;
--update)
  Term --update
  ;;
--checkupdates)
  Term --checkupdates
  ;;
--netmanager)
  NetManagerDM
  ;;
--bluetooth)
  rofi-bluetooth
  ;;
--clipboard)
  clipcat-menu
  ;;
--screenshot)
  ScreenShoTer
  ;;
--powermenu)
  PowerMenu
  ;;
--android)
  AndroidMount
  ;;
--keyboard)
  KeyBoardL
  ;;
--yazi)
  Term --yazi
  ;;
--nvim)
  Term --nvim
  ;;
--music)
  Term --music
  ;;
--fetch)
  Term --fetch
  ;;
--scratch)
  Term --floating
  ;;
--yaziscratch)
  Term --yaziscratch
  ;;
  # Apps
--filemanager)
  ranger
  ;;
--browser)
  librewolf
  ;;
--editor)
  nvim
  ;;
--telegram)
  signal-desktop
  ;;
--whats)
  firefox -new-tab https://web.whatsapp.com/
  ;;
--soundcontrol)
  pavucontrol
  ;;
  # Eww Widgets
--KeyHelp)
  eww -c "$WIDGET_DIR" open --toggle csheet
  ;;
--usercard)
  eww -c "$WIDGET_DIR" open --toggle launchermenu
  ;;
--player)
  eww -c "$WIDGET_DIR" open --toggle music
  ;;
--calendar)
  eww -c "$WIDGET_DIR" open --toggle date
  ;;
*)
  echo "Invalid Option"
  ;;
esac
